name: GitHub Classroom Workflow
on: [push]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run RabbitMQ
        run: docker-compose up -d rabbitmq
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.10'
      - uses: education/autograding@v1
